/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function greet(): void;
export function __wbg_program_free(a: number): void;
export function __wbg_get_program_finished(a: number): number;
export function __wbg_set_program_finished(a: number, b: number): void;
export function program_new(a: number, b: number): number;
export function program_step(a: number, b: number): number;
export function program_ram_size(a: number): number;
export function program_display_size(a: number): number;
export function program_set_display(a: number, b: number, c: number): void;
export function program_ram(a: number): number;
export function program_display(a: number): number;
export function program_keyboard(a: number): number;
export function program_end(a: number): void;
export function __wbg_wasmbindgentestcontext_free(a: number): void;
export function wasmbindgentestcontext_new(): number;
export function wasmbindgentestcontext_args(a: number, b: number, c: number): void;
export function wasmbindgentestcontext_run(a: number, b: number, c: number): number;
export function __wbgtest_console_log(a: number): void;
export function __wbgtest_console_debug(a: number): void;
export function __wbgtest_console_info(a: number): void;
export function __wbgtest_console_warn(a: number): void;
export function __wbgtest_console_error(a: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hf71a1f40830d1442(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke3_mut__h0687db71c25e9b76(a: number, b: number, c: number, d: number, e: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h0ea87d110024de41(a: number, b: number, c: number, d: number): void;
